<?php

namespace Database\Seeders;

use App\Models\Species;
use Illuminate\Database\Seeder;

class SpeciesSeeder extends Seeder
{
    public function run(): void
    {
        $species = [
            "Wolf",
            "Fox",
            "Dragon",
            "Husky",
            "Tiger",
            "Dog",
            "cat",
            "Lion",
            "Sergal",
            "German Shepherd",
            "Folf",
            "Dutch Angel Dragon",
            "Red Fox",
            "Lynx",
            "Red Panda",
            "Hyena",
            "Arctic Fox",
            "Raccoon",
            "Deer",
            "Werewolf",
            "Coyote",
            "Border Collie",
            "Protogen",
            "Otter",
            "Bunny",
            "Wusky",
            "Fennec",
            "Horse",
            "Cheetah",
            "Canine",
            "Gryphon",
            "Furdragon",
            "Maned wolf",
            "Corgi",
            "Opossum",
            "Bat",
            "Jackal",
            "Striped Hyena",
            "Fennec Fox",
            "Manokit",
            "Raptor",
            "Rat",
            "Rexouium",
            "Australian Shepherd",
            "Domestic Cat",
            "Avali",
            "Eiswolf",
            "Hellhound",
            "Collie ",
            "Donkey",
            "House Cat",
            "Fusky",
            "Digimon",
            "Siberian Tiger",
            "Shiba inu",
            "Kitsune",
            "Grey Wolf",
            "Silver Fox",
            "Gray Fox",
            "Dhole",
            "Ferret",
            "White Tiger",
            "Western Dragon",
            "Kobold",
            "Lioness",
            "Feline",
            "Rabbit",
            "Snow Leopard",
            "Doberman",
            "Vixen",
            "African Wild Dog",
            "Siberian Husky",
            "Akita",
            "Wickerbeast",
            "Demon Wolf",
            "Kangaroo",
            "Angel Dragon",
            "Demon",
            "Skulldog",
            "Umbreon",
            "Hybrid",
            "Thundra-Wolf",
            "Squirrel",
            "Skunk",
            "Panther",
            "Caribou",
            "Bunny",
            "Shark",
            "Wolf/Fox",
            "Golden Retriever",
            "Lizard",
            "Demon Cat",
            "DinoDog",
            "Spotted Hyena",
            "Fluffy Dragon",
            "Snowleopard",
            "Eastern Dragon",
            "Redfox",
            "Aardwolf",
            "Pony",
        ];
        // Create if not exists already
        Species::upsert(
            collect($species)->map(fn ($name) => ['name' => $name,'checked' => true])->toArray(),
            ['name'],
            ['name','checked']
        );
    }
}
