openapi: 3.0.3
info:
  title: Fursuit Registration Tool API
  description: API for managing fursuit badge registration at Eurofurence convention
  version: 1.0.0
  contact:
    name: Fursuit Registration Team
    url: https://github.com/eurofurence/fursuit-reg-tool
servers:
  - url: http://localhost/api
    description: Local development server
  - url: https://fursuit.eurofurence.org/api
    description: Production server for Eurofurence Fursuit Registration Tool
paths:
  /fursuits:
    get:
      summary: Search fursuits
      description: Retrieve a paginated list of fursuits from the currently active event with optional filtering by attendee ID, name, and status
      operationId: searchFursuits
      security:
        - bearerAuth: []
      parameters:
        - name: reg_id
          in: query
          description: Filter by attendee registration ID
          required: false
          schema:
            type: string
            example: "1"
        - name: name
          in: query
          description: Filter by fursuit name (partial match supported)
          required: false
          schema:
            type: string
            maxLength: 64
            example: "Wolf"
        - name: status
          in: query
          description: Filter by fursuit approval status
          required: false
          schema:
            type: string
            enum:
              - pending
              - approved
              - rejected
              - any
            default: approved
            example: "approved"
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
      responses:
        '200':
          description: Successful response with paginated fursuit data from the active event. Returns empty array if no active event exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Fursuit'
                    description: Array of fursuits from the currently active event only
                  links:
                    $ref: '#/components/schemas/PaginationLinks'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
              example:
                data:
                  - id: 1
                    reg_id: "1"
                    status: "approved"
                    name: "Fluffy Wolf"
                    published: true
                    catch_em_all: true
                    image_url: "https://example.com/images/fursuit1.jpg"
                    badges_count: 2
                    user:
                      id: 42
                      name: "John Doe"
                    species:
                      id: 1
                      name: "Wolf"
                      type: "Canine"
                links:
                  first: "http://localhost/api/fursuits?page=1"
                  last: "http://localhost/api/fursuits?page=5"
                  prev: null
                  next: "http://localhost/api/fursuits?page=2"
                meta:
                  current_page: 1
                  from: 1
                  last_page: 5
                  per_page: 10
                  to: 10
                  total: 45
        '401':
          description: Unauthorized - Invalid or missing bearer token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Unauthenticated."
        '403':
          description: Forbidden - Invalid bearer token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Forbidden."
        '422':
          description: Validation error - Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                message: "The given data was invalid."
                errors:
                  reg_id:
                    - "The selected reg id is invalid."
                  name:
                    - "The name must not be greater than 64 characters."
                  status:
                    - "The selected status is invalid."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Server Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Bearer token authentication required for all API endpoints

  schemas:
    Fursuit:
      type: object
      description: Fursuit object containing details about a registered fursuit
      properties:
        id:
          type: integer
          description: Unique identifier for the fursuit
          example: 1
        reg_id:
          type: string
          nullable: true
          description: Attendee registration ID associated with the fursuit owner
          example: "1"
        status:
          type: string
          description: Current approval status of the fursuit
          enum:
            - pending
            - approved
            - rejected
          example: "approved"
        name:
          type: string
          description: Name of the fursuit character
          example: "Fluffy Wolf"
        published:
          type: boolean
          description: Whether the fursuit is published and visible to the public
          example: true
        catch_em_all:
          type: boolean
          description: Whether the fursuit participates in the Catch-Em-All game
          example: true
        image_url:
          type: string
          nullable: true
          format: uri
          description: URL to the fursuit's image
          example: "https://example.com/images/fursuit1.jpg"
        badges_count:
          type: integer
          description: Number of badges associated with this fursuit
          example: 2
        user:
          $ref: '#/components/schemas/User'
        species:
          $ref: '#/components/schemas/Species'
      required:
        - id
        - status
        - name
        - published
        - catch_em_all
        - badges_count
        - user
        - species

    User:
      type: object
      description: Basic user information
      properties:
        id:
          type: integer
          description: Unique identifier for the user
          example: 42
        name:
          type: string
          description: Display name of the user
          example: "John Doe"
      required:
        - id
        - name

    Species:
      type: object
      description: Species information for the fursuit
      properties:
        id:
          type: integer
          description: Unique identifier for the species
          example: 1
        name:
          type: string
          description: Name of the species
          example: "Wolf"
        type:
          type: string
          description: Type or category of the species
          example: "Canine"
      required:
        - id
        - name

    PaginationLinks:
      type: object
      description: Pagination navigation links
      properties:
        first:
          type: string
          format: uri
          description: URL to the first page
          example: "http://localhost/api/fursuits?page=1"
        last:
          type: string
          format: uri
          description: URL to the last page
          example: "http://localhost/api/fursuits?page=5"
        prev:
          type: string
          format: uri
          nullable: true
          description: URL to the previous page (null if on first page)
          example: null
        next:
          type: string
          format: uri
          nullable: true
          description: URL to the next page (null if on last page)
          example: "http://localhost/api/fursuits?page=2"
      required:
        - first
        - last

    PaginationMeta:
      type: object
      description: Pagination metadata
      properties:
        current_page:
          type: integer
          description: Current page number
          example: 1
        from:
          type: integer
          nullable: true
          description: First item number on current page
          example: 1
        last_page:
          type: integer
          description: Total number of pages
          example: 5
        per_page:
          type: integer
          description: Number of items per page
          example: 10
        to:
          type: integer
          nullable: true
          description: Last item number on current page
          example: 10
        total:
          type: integer
          description: Total number of items
          example: 45
      required:
        - current_page
        - last_page
        - per_page
        - total

    Error:
      type: object
      description: Standard error response
      properties:
        message:
          type: string
          description: Human-readable error message
          example: "Server Error"
      required:
        - message

    ValidationError:
      type: object
      description: Validation error response with detailed field errors
      properties:
        message:
          type: string
          description: General validation error message
          example: "The given data was invalid."
        errors:
          type: object
          description: Field-specific validation errors
          additionalProperties:
            type: array
            items:
              type: string
          example:
            reg_id:
              - "The selected reg id is invalid."
            name:
              - "The name must not be greater than 64 characters."
      required:
        - message
        - errors

tags:
  - name: fursuits
    description: Operations related to fursuit management and searching
