<script setup>
/**
 * Resolves the kebab-case icon names the server sends (Status::make, Action::icon,
 * Navigation items) to lucide components. Named imports keep this tree-shakeable, and
 * an unknown name renders nothing rather than throwing.
 *
 * Every name below was checked against the installed lucide-vue-next 0.536.0, which is
 * older than the 0.542.0 the ef-streaming original was written against.
 */
import { computed } from 'vue';
import {
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CircleUser,
  CircleX,
  Clock,
  Code,
  Cog,
  Columns3,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Hand,
  Hourglass,
  IdCard,
  ImageIcon,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link2,
  ListOrdered,
  Loader,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minus,
  Monitor,
  PackageCheck,
  PanelLeft,
  Pause,
  Pencil,
  Play,
  Plus,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  RotateCcw,
  Search,
  Server,
  ShieldCheck,
  ShieldOff,
  ShoppingCart,
  Signal,
  SignalZero,
  SlidersHorizontal,
  Square,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  Wrench,
  X,
} from 'lucide-vue-next';

const icons = {
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  ban: Ban,
  'bar-chart': BarChart3,
  calendar: CalendarDays,
  'calendar-days': CalendarDays,
  camera: Camera,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  'circle-minus': CircleMinus,
  'circle-pause': CirclePause,
  'circle-user': CircleUser,
  'circle-x': CircleX,
  clock: Clock,
  code: Code,
  cog: Cog,
  columns: Columns3,
  copy: Copy,
  'credit-card': CreditCard,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  hand: Hand,
  hourglass: Hourglass,
  'id-card': IdCard,
  image: ImageIcon,
  info: Info,
  key: KeyRound,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  link: Link2,
  'list-ordered': ListOrdered,
  loader: Loader,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  // Settings > On-Site Desk: the badge desk is a place attendees walk to.
  'map-pin': MapPin,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  'package-check': PackageCheck,
  'panel-left': PanelLeft,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  printer: Printer,
  'qr-code': QrCode,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  search: Search,
  server: Server,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  'shopping-cart': ShoppingCart,
  signal: Signal,
  'signal-zero': SignalZero,
  'sliders-horizontal': SlidersHorizontal,
  square: Square,
  // The PDF Generator's box-labels download: a label, not a box.
  tag: Tag,
  'trash-2': Trash2,
  // The dashboard's comparison stats, successors to heroicon-m-arrow-trending-up/down.
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  wrench: Wrench,
  x: X,
};

const props = defineProps({
  name: { type: String, default: null },
  size: { type: Number, default: 14 },
});

const component = computed(() => (props.name ? icons[props.name] ?? null : null));
</script>

<template>
  <component :is="component" v-if="component" :size="size" :stroke-width="1.75" />
</template>
