on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
      - "v[0-9]+.[0-9]+.[0-9]-**"

jobs:
  build-and-push-image:
    uses: eurofurence/workflows/.github/workflows/docker-buildx-push.yml@main
    permissions:
      contents: read
      packages: write
    with:
      # build-args: "--build-arg FOO=bar"
      # build-context: .
      dockerfile: ./Dockerfile
      image-name: ${{ github.repository }}
    secrets:
      ghcr-token: ${{ secrets.GITHUB_TOKEN }}
